# version: "3.3"
# services:
#   postgres:
#     image: postgres:13
#     environment:
#       - POSTGRES_DB=autopartes_delta
#       - POSTGRES_USER=user
#       - POSTGRES_PASSWORD=admin123
#     ports:
#       - 5432:5432
#     volumes:
#       - ./postgres_data:/var/lib/postgresql/data
#   pgadmin:
#     image: dpage/pgadmin4
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=admin@mail.com
#       - PGADMIN_DEFAULT_PASSWORD=root
#     ports:
#       - 5050:80

version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'autopartes_delta'   
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - 3306:3306
    volumes:
      - ./my-db:/var/lib/mysql


